/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fusion_qt_nativeqt_QtNativeCalls */

#ifndef _Included_org_fusion_qt_nativeqt_QtNativeCalls
#define _Included_org_fusion_qt_nativeqt_QtNativeCalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fusion_qt_nativeqt_QtNativeCalls
 * Method:    fromPlatformHandle
 * Signature: (J)Lcom/trolltech/qt/gui/QWidget;
 */
JNIEXPORT jobject JNICALL Java_org_fusion_qt_nativeqt_QtNativeCalls_fromPlatformHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_fusion_qt_nativeqt_QtNativeCalls
 * Method:    setOverrideRedirect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_fusion_qt_nativeqt_QtNativeCalls_setOverrideRedirect
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
